#pragma once

#ifdef __cplusplus
extern "C" {
#endif

// DBC file version
#define VER_HYTECH_MAJ_FMON (6U)
#define VER_HYTECH_MIN_FMON (0U)

#include "hytech-config.h"

#ifdef HYTECH_USE_DIAG_MONITORS

#include "canmonitorutil.h"
/*
This file contains the prototypes of all the functions that will be called
from each Unpack_*name* function to detect DBC related errors
It is the user responsibility to defined these functions in the
separated .c file. If it won't be done the linkage error will happen
*/

#ifdef HYTECH_USE_MONO_FMON

void _FMon_MONO_hytech(FrameMonitor_t* _mon, uint32_t msgid);

#define FMon_IMU_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_State_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_Settings_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_Velocities_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_Attitude_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_Configuration_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV1_STATUS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV1_TEMPS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV1_DYNAMICS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV1_POWER_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV1_FEEDBACK_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV2_STATUS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV2_TEMPS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV2_DYNAMICS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV2_POWER_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV2_FEEDBACK_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV3_STATUS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV3_TEMPS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV3_DYNAMICS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV3_POWER_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV3_FEEDBACK_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV4_STATUS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV4_TEMPS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV4_DYNAMICS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV4_POWER_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV4_FEEDBACK_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV1_CONTROL_WORD_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV2_CONTROL_WORD_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV3_CONTROL_WORD_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV4_CONTROL_WORD_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_TCU_DRIVER_MSG_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_TCU_LAP_TIMES_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV1_CONTROL_INPUT_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV2_CONTROL_INPUT_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV3_CONTROL_INPUT_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_MC1_ENERGY_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_PEDALS_SYSTEM_DATA_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_MCU_STATUS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_MCU_LOAD_CELLS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_MCU_FRONT_POTS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_MCU_SUSPENSION_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_TC_SIMPLE_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_TC_SIMPLE_LAUNCH_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_BRAKE_PRESSURE_SENSOR_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_MCU_ANALOG_READINGS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_MCU_PEDAL_RAW_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_VN_VEL_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_VN_LINEAR_ACCEL_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_VN_LINEAR_ACCEL_UNCOMP_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_VN_YPR_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_VN_LAT_LON_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_BMS_ONBOARD_TEMPS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_BMS_ONBOARD_DETAILED_TEMPS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_BMS_VOLTAGES_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_BMS_DETAILED_VOLTAGES_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_BMS_TEMPS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_BMS_DETAILED_TEMPS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_BMS_STATUS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_CCU_STATUS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_PENTHOUSE_ACCUM_MSG_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_VN_GPS_TIME_MSG_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_VN_STATUS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_BMS_COULOMB_COUNTS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_VN_ANGULAR_RATE_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_REAR_SUSPENSION_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_SAB_THERMISTORS_1_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_SAB_THERMISTORS_2_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_VN_ECEF_POS_XY_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_TCU_STATUS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_VN_ECEF_POS_Z_MSG_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_VN_GNSS_COMP_SIG_HEALTH_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_DASHBOARD_MCU_STATE_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_DASHBOARD_STATE_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_FRONT_SUSPENSION_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_DRIVEBRAIN_TORQUE_LIM_INPUT_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_DRIVEBRAIN_SPEED_SET_INPUT_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_DRIVEBRAIN_DESIRED_TORQUE_INPUT_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_FRONT_THERMISTORS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_EM_MEASUREMENT_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_MCU_ERROR_STATES_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV4_CONTROL_INPUT_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV1_CONTROL_PARAMETER_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV2_CONTROL_PARAMETER_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV3_CONTROL_PARAMETER_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV4_CONTROL_PARAMETER_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_ENERGY_METER_MEAS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_DRIVETRAIN_COMMAND_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV1_OVERLOAD_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV2_OVERLOAD_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV3_OVERLOAD_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_INV4_OVERLOAD_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_DRIVETRAIN_RPMS_TELEM_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_DRIVETRAIN_ERR_STATUS_TELEM_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_DRIVETRAIN_STATUS_TELEM_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_DRIVETRAIN_TORQUE_TELEM_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_DRIVETRAIN_FILTER_OUT_TORQUE_TEL_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_CAR_STATES_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_DRIVEBRAIN_STATE_DATA_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_DASH_INPUT_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_AERO_PRESSURE_SENSOR_22_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_AERO_PRESSURE_SENSOR_32_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_AERO_PRESSURE_SENSOR_42_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_AERO_PRESSURE_SENSOR_11_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_AERO_PRESSURE_SENSOR_12_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_EM_STATUS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_ACU_SHUNT_MEASUREMENTS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_ENERGY_METER_STATUS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_STATE_OF_CHARGE_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_STEERING_DATA_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_LF_TTPMS_1_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_LF_TTPMS_2_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_LF_TTPMS_3_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_LF_TTPMS_4_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_LF_TTPMS_5_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_LF_TTPMS_6_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_LR_TTPMS_1_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_LR_TTPMS_2_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_LR_TTPMS_3_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_LR_TTPMS_4_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_LR_TTPMS_5_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_LR_TTPMS_6_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_RF_TTPMS_1_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_RF_TTPMS_2_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_RF_TTPMS_3_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_RF_TTPMS_4_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_RF_TTPMS_5_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_RF_TTPMS_6_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_RR_TTPMS_1_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_RR_TTPMS_2_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_RR_TTPMS_3_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_RR_TTPMS_4_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_RR_TTPMS_5_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_RR_TTPMS_6_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_BRAKE_ROTOR_SENSOR_COMMAND_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_FL_BRAKE_ROTOR_TEMP_CH1_CH4_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_FL_BRAKE_ROTOR_TEMP_CH5_CH8_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_FL_BRAKE_ROTOR_TEMP_CH9_CH12_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_FL_BRAKE_ROTOR_TEMP_CH13_CH16_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_FL_BRAKE_ROTOR_SENSOR_TEMP_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_FR_BRAKE_ROTOR_TEMP_CH1_CH4_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_FR_BRAKE_ROTOR_TEMP_CH5_CH8_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_FR_BRAKE_ROTOR_TEMP_CH9_CH12_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_FR_BRAKE_ROTOR_TEMP_CH13_CH16_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_FR_BRAKE_ROTOR_SENSOR_TEMP_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_CONTROLLER_PID_TV_DATA_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_CONTROLLER_PID_TV_DELTA_DATA_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_TCMUX_STATUS_REPORT_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_ACU_OK_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_ENERGY_METER_TEMP_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_AERO_PRESSURE_SENSOR_21_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_AERO_PRESSURE_SENSOR_31_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_AERO_PRESSURE_SENSOR_41_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_CONTROLLER_TCS_PID_OUTPUT_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_VEHM_WHEEL_LIN_VEL_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_CONTROLLER_TORQUE_BIAS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_CONTROLLER_REGEN_5KPH_TORQUE_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_CONTROLLER_REGEN_5KPH_STATUS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_CONTROLLER_TCS_PID_CONFIG_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_CONTROLLER_YAW_PID_CONFIG_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_CONTROLLER_TCS_SATURATION_CONFIG_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_CONTROLLER_TCS_CONFIG_CONT_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_CONTROLLER_TCS_DIFF_CONFIG_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_CONTROLLER_TCS_RPM_SCHE_CONFIG_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_CONTROLLER_TCS_SLIP_TARGETS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_VEHM_WHEEL_STEER_AVG_DEG_MSG_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_VEHM_KIN_DES_YAW_RATE_RAD_S_MSG_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_CONTROLLER_TCS_NL_SCHE_CONFIG_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_CONTROLLER_PID_YAW_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_VEHM_LONG_CORNER_VEL_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_VEHM_SL_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_CONTROLLER_PID_YAW_TORQUE_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_CONTROLLER_NORMAL_DIST_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_CONTROLLER_NORMAL_TORQUE_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_CONTROLLER_POWER_LIM_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_CONTROLLER_POWER_LIM_CORNER_POW_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_CONTROLLER_POWER_LIM_TORQUE_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_CONTROLLER_BOOLEAN_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_VEHM_BETA_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_DASHBOARD_BUZZER_CONTROL_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_CONTROLLER_TORQUE_SETUP_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_CONTROLLER_TCS_CONFIG_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_CONTROLLER_TCS_TORQUE_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_CONTROLLER_TCS_STATUS_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_CONTROLLER_TCS_PID_INPUT_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_VEHM_ALPHA_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_CHARGER_CONTROL_hytech(x, y) _FMon_MONO_hytech((x), (y))
#define FMon_CHARGER_DATA_hytech(x, y) _FMon_MONO_hytech((x), (y))

#else

void _FMon_IMU_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_State_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_Settings_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_Velocities_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_Attitude_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_Configuration_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV1_STATUS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV1_TEMPS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV1_DYNAMICS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV1_POWER_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV1_FEEDBACK_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV2_STATUS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV2_TEMPS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV2_DYNAMICS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV2_POWER_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV2_FEEDBACK_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV3_STATUS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV3_TEMPS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV3_DYNAMICS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV3_POWER_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV3_FEEDBACK_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV4_STATUS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV4_TEMPS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV4_DYNAMICS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV4_POWER_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV4_FEEDBACK_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV1_CONTROL_WORD_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV2_CONTROL_WORD_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV3_CONTROL_WORD_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV4_CONTROL_WORD_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_TCU_DRIVER_MSG_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_TCU_LAP_TIMES_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV1_CONTROL_INPUT_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV2_CONTROL_INPUT_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV3_CONTROL_INPUT_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_MC1_ENERGY_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_PEDALS_SYSTEM_DATA_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_MCU_STATUS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_MCU_LOAD_CELLS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_MCU_FRONT_POTS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_MCU_SUSPENSION_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_TC_SIMPLE_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_TC_SIMPLE_LAUNCH_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_BRAKE_PRESSURE_SENSOR_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_MCU_ANALOG_READINGS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_MCU_PEDAL_RAW_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_VN_VEL_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_VN_LINEAR_ACCEL_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_VN_LINEAR_ACCEL_UNCOMP_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_VN_YPR_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_VN_LAT_LON_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_BMS_ONBOARD_TEMPS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_BMS_ONBOARD_DETAILED_TEMPS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_BMS_VOLTAGES_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_BMS_DETAILED_VOLTAGES_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_BMS_TEMPS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_BMS_DETAILED_TEMPS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_BMS_STATUS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_CCU_STATUS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_PENTHOUSE_ACCUM_MSG_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_VN_GPS_TIME_MSG_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_VN_STATUS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_BMS_COULOMB_COUNTS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_VN_ANGULAR_RATE_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_REAR_SUSPENSION_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_SAB_THERMISTORS_1_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_SAB_THERMISTORS_2_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_VN_ECEF_POS_XY_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_TCU_STATUS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_VN_ECEF_POS_Z_MSG_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_VN_GNSS_COMP_SIG_HEALTH_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_DASHBOARD_MCU_STATE_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_DASHBOARD_STATE_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_FRONT_SUSPENSION_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_DRIVEBRAIN_TORQUE_LIM_INPUT_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_DRIVEBRAIN_SPEED_SET_INPUT_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_DRIVEBRAIN_DESIRED_TORQUE_INPUT_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_FRONT_THERMISTORS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_EM_MEASUREMENT_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_MCU_ERROR_STATES_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV4_CONTROL_INPUT_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV1_CONTROL_PARAMETER_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV2_CONTROL_PARAMETER_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV3_CONTROL_PARAMETER_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV4_CONTROL_PARAMETER_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_ENERGY_METER_MEAS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_DRIVETRAIN_COMMAND_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV1_OVERLOAD_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV2_OVERLOAD_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV3_OVERLOAD_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_INV4_OVERLOAD_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_DRIVETRAIN_RPMS_TELEM_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_DRIVETRAIN_ERR_STATUS_TELEM_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_DRIVETRAIN_STATUS_TELEM_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_DRIVETRAIN_TORQUE_TELEM_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_DRIVETRAIN_FILTER_OUT_TORQUE_TEL_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_CAR_STATES_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_DRIVEBRAIN_STATE_DATA_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_DASH_INPUT_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_AERO_PRESSURE_SENSOR_22_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_AERO_PRESSURE_SENSOR_32_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_AERO_PRESSURE_SENSOR_42_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_AERO_PRESSURE_SENSOR_11_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_AERO_PRESSURE_SENSOR_12_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_EM_STATUS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_ACU_SHUNT_MEASUREMENTS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_ENERGY_METER_STATUS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_STATE_OF_CHARGE_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_STEERING_DATA_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_LF_TTPMS_1_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_LF_TTPMS_2_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_LF_TTPMS_3_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_LF_TTPMS_4_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_LF_TTPMS_5_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_LF_TTPMS_6_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_LR_TTPMS_1_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_LR_TTPMS_2_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_LR_TTPMS_3_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_LR_TTPMS_4_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_LR_TTPMS_5_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_LR_TTPMS_6_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_RF_TTPMS_1_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_RF_TTPMS_2_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_RF_TTPMS_3_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_RF_TTPMS_4_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_RF_TTPMS_5_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_RF_TTPMS_6_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_RR_TTPMS_1_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_RR_TTPMS_2_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_RR_TTPMS_3_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_RR_TTPMS_4_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_RR_TTPMS_5_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_RR_TTPMS_6_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_BRAKE_ROTOR_SENSOR_COMMAND_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_FL_BRAKE_ROTOR_TEMP_CH1_CH4_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_FL_BRAKE_ROTOR_TEMP_CH5_CH8_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_FL_BRAKE_ROTOR_TEMP_CH9_CH12_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_FL_BRAKE_ROTOR_TEMP_CH13_CH16_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_FL_BRAKE_ROTOR_SENSOR_TEMP_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_FR_BRAKE_ROTOR_TEMP_CH1_CH4_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_FR_BRAKE_ROTOR_TEMP_CH5_CH8_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_FR_BRAKE_ROTOR_TEMP_CH9_CH12_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_FR_BRAKE_ROTOR_TEMP_CH13_CH16_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_FR_BRAKE_ROTOR_SENSOR_TEMP_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_CONTROLLER_PID_TV_DATA_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_CONTROLLER_PID_TV_DELTA_DATA_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_TCMUX_STATUS_REPORT_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_ACU_OK_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_ENERGY_METER_TEMP_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_AERO_PRESSURE_SENSOR_21_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_AERO_PRESSURE_SENSOR_31_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_AERO_PRESSURE_SENSOR_41_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_CONTROLLER_TCS_PID_OUTPUT_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_VEHM_WHEEL_LIN_VEL_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_CONTROLLER_TORQUE_BIAS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_CONTROLLER_REGEN_5KPH_TORQUE_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_CONTROLLER_REGEN_5KPH_STATUS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_CONTROLLER_TCS_PID_CONFIG_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_CONTROLLER_YAW_PID_CONFIG_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_CONTROLLER_TCS_SATURATION_CONFIG_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_CONTROLLER_TCS_CONFIG_CONT_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_CONTROLLER_TCS_DIFF_CONFIG_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_CONTROLLER_TCS_RPM_SCHE_CONFIG_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_CONTROLLER_TCS_SLIP_TARGETS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_VEHM_WHEEL_STEER_AVG_DEG_MSG_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_VEHM_KIN_DES_YAW_RATE_RAD_S_MSG_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_CONTROLLER_TCS_NL_SCHE_CONFIG_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_CONTROLLER_PID_YAW_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_VEHM_LONG_CORNER_VEL_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_VEHM_SL_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_CONTROLLER_PID_YAW_TORQUE_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_CONTROLLER_NORMAL_DIST_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_CONTROLLER_NORMAL_TORQUE_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_CONTROLLER_POWER_LIM_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_CONTROLLER_POWER_LIM_CORNER_POW_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_CONTROLLER_POWER_LIM_TORQUE_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_CONTROLLER_BOOLEAN_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_VEHM_BETA_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_DASHBOARD_BUZZER_CONTROL_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_CONTROLLER_TORQUE_SETUP_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_CONTROLLER_TCS_CONFIG_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_CONTROLLER_TCS_TORQUE_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_CONTROLLER_TCS_STATUS_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_CONTROLLER_TCS_PID_INPUT_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_VEHM_ALPHA_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_CHARGER_CONTROL_hytech(FrameMonitor_t* _mon, uint32_t msgid);
void _FMon_CHARGER_DATA_hytech(FrameMonitor_t* _mon, uint32_t msgid);

#define FMon_IMU_hytech(x, y) _FMon_IMU_hytech((x), (y))
#define FMon_State_hytech(x, y) _FMon_State_hytech((x), (y))
#define FMon_Settings_hytech(x, y) _FMon_Settings_hytech((x), (y))
#define FMon_Velocities_hytech(x, y) _FMon_Velocities_hytech((x), (y))
#define FMon_Attitude_hytech(x, y) _FMon_Attitude_hytech((x), (y))
#define FMon_Configuration_hytech(x, y) _FMon_Configuration_hytech((x), (y))
#define FMon_INV1_STATUS_hytech(x, y) _FMon_INV1_STATUS_hytech((x), (y))
#define FMon_INV1_TEMPS_hytech(x, y) _FMon_INV1_TEMPS_hytech((x), (y))
#define FMon_INV1_DYNAMICS_hytech(x, y) _FMon_INV1_DYNAMICS_hytech((x), (y))
#define FMon_INV1_POWER_hytech(x, y) _FMon_INV1_POWER_hytech((x), (y))
#define FMon_INV1_FEEDBACK_hytech(x, y) _FMon_INV1_FEEDBACK_hytech((x), (y))
#define FMon_INV2_STATUS_hytech(x, y) _FMon_INV2_STATUS_hytech((x), (y))
#define FMon_INV2_TEMPS_hytech(x, y) _FMon_INV2_TEMPS_hytech((x), (y))
#define FMon_INV2_DYNAMICS_hytech(x, y) _FMon_INV2_DYNAMICS_hytech((x), (y))
#define FMon_INV2_POWER_hytech(x, y) _FMon_INV2_POWER_hytech((x), (y))
#define FMon_INV2_FEEDBACK_hytech(x, y) _FMon_INV2_FEEDBACK_hytech((x), (y))
#define FMon_INV3_STATUS_hytech(x, y) _FMon_INV3_STATUS_hytech((x), (y))
#define FMon_INV3_TEMPS_hytech(x, y) _FMon_INV3_TEMPS_hytech((x), (y))
#define FMon_INV3_DYNAMICS_hytech(x, y) _FMon_INV3_DYNAMICS_hytech((x), (y))
#define FMon_INV3_POWER_hytech(x, y) _FMon_INV3_POWER_hytech((x), (y))
#define FMon_INV3_FEEDBACK_hytech(x, y) _FMon_INV3_FEEDBACK_hytech((x), (y))
#define FMon_INV4_STATUS_hytech(x, y) _FMon_INV4_STATUS_hytech((x), (y))
#define FMon_INV4_TEMPS_hytech(x, y) _FMon_INV4_TEMPS_hytech((x), (y))
#define FMon_INV4_DYNAMICS_hytech(x, y) _FMon_INV4_DYNAMICS_hytech((x), (y))
#define FMon_INV4_POWER_hytech(x, y) _FMon_INV4_POWER_hytech((x), (y))
#define FMon_INV4_FEEDBACK_hytech(x, y) _FMon_INV4_FEEDBACK_hytech((x), (y))
#define FMon_INV1_CONTROL_WORD_hytech(x, y) _FMon_INV1_CONTROL_WORD_hytech((x), (y))
#define FMon_INV2_CONTROL_WORD_hytech(x, y) _FMon_INV2_CONTROL_WORD_hytech((x), (y))
#define FMon_INV3_CONTROL_WORD_hytech(x, y) _FMon_INV3_CONTROL_WORD_hytech((x), (y))
#define FMon_INV4_CONTROL_WORD_hytech(x, y) _FMon_INV4_CONTROL_WORD_hytech((x), (y))
#define FMon_TCU_DRIVER_MSG_hytech(x, y) _FMon_TCU_DRIVER_MSG_hytech((x), (y))
#define FMon_TCU_LAP_TIMES_hytech(x, y) _FMon_TCU_LAP_TIMES_hytech((x), (y))
#define FMon_INV1_CONTROL_INPUT_hytech(x, y) _FMon_INV1_CONTROL_INPUT_hytech((x), (y))
#define FMon_INV2_CONTROL_INPUT_hytech(x, y) _FMon_INV2_CONTROL_INPUT_hytech((x), (y))
#define FMon_INV3_CONTROL_INPUT_hytech(x, y) _FMon_INV3_CONTROL_INPUT_hytech((x), (y))
#define FMon_MC1_ENERGY_hytech(x, y) _FMon_MC1_ENERGY_hytech((x), (y))
#define FMon_PEDALS_SYSTEM_DATA_hytech(x, y) _FMon_PEDALS_SYSTEM_DATA_hytech((x), (y))
#define FMon_MCU_STATUS_hytech(x, y) _FMon_MCU_STATUS_hytech((x), (y))
#define FMon_MCU_LOAD_CELLS_hytech(x, y) _FMon_MCU_LOAD_CELLS_hytech((x), (y))
#define FMon_MCU_FRONT_POTS_hytech(x, y) _FMon_MCU_FRONT_POTS_hytech((x), (y))
#define FMon_MCU_SUSPENSION_hytech(x, y) _FMon_MCU_SUSPENSION_hytech((x), (y))
#define FMon_TC_SIMPLE_hytech(x, y) _FMon_TC_SIMPLE_hytech((x), (y))
#define FMon_TC_SIMPLE_LAUNCH_hytech(x, y) _FMon_TC_SIMPLE_LAUNCH_hytech((x), (y))
#define FMon_BRAKE_PRESSURE_SENSOR_hytech(x, y) _FMon_BRAKE_PRESSURE_SENSOR_hytech((x), (y))
#define FMon_MCU_ANALOG_READINGS_hytech(x, y) _FMon_MCU_ANALOG_READINGS_hytech((x), (y))
#define FMon_MCU_PEDAL_RAW_hytech(x, y) _FMon_MCU_PEDAL_RAW_hytech((x), (y))
#define FMon_VN_VEL_hytech(x, y) _FMon_VN_VEL_hytech((x), (y))
#define FMon_VN_LINEAR_ACCEL_hytech(x, y) _FMon_VN_LINEAR_ACCEL_hytech((x), (y))
#define FMon_VN_LINEAR_ACCEL_UNCOMP_hytech(x, y) _FMon_VN_LINEAR_ACCEL_UNCOMP_hytech((x), (y))
#define FMon_VN_YPR_hytech(x, y) _FMon_VN_YPR_hytech((x), (y))
#define FMon_VN_LAT_LON_hytech(x, y) _FMon_VN_LAT_LON_hytech((x), (y))
#define FMon_BMS_ONBOARD_TEMPS_hytech(x, y) _FMon_BMS_ONBOARD_TEMPS_hytech((x), (y))
#define FMon_BMS_ONBOARD_DETAILED_TEMPS_hytech(x, y) _FMon_BMS_ONBOARD_DETAILED_TEMPS_hytech((x), (y))
#define FMon_BMS_VOLTAGES_hytech(x, y) _FMon_BMS_VOLTAGES_hytech((x), (y))
#define FMon_BMS_DETAILED_VOLTAGES_hytech(x, y) _FMon_BMS_DETAILED_VOLTAGES_hytech((x), (y))
#define FMon_BMS_TEMPS_hytech(x, y) _FMon_BMS_TEMPS_hytech((x), (y))
#define FMon_BMS_DETAILED_TEMPS_hytech(x, y) _FMon_BMS_DETAILED_TEMPS_hytech((x), (y))
#define FMon_BMS_STATUS_hytech(x, y) _FMon_BMS_STATUS_hytech((x), (y))
#define FMon_CCU_STATUS_hytech(x, y) _FMon_CCU_STATUS_hytech((x), (y))
#define FMon_PENTHOUSE_ACCUM_MSG_hytech(x, y) _FMon_PENTHOUSE_ACCUM_MSG_hytech((x), (y))
#define FMon_VN_GPS_TIME_MSG_hytech(x, y) _FMon_VN_GPS_TIME_MSG_hytech((x), (y))
#define FMon_VN_STATUS_hytech(x, y) _FMon_VN_STATUS_hytech((x), (y))
#define FMon_BMS_COULOMB_COUNTS_hytech(x, y) _FMon_BMS_COULOMB_COUNTS_hytech((x), (y))
#define FMon_VN_ANGULAR_RATE_hytech(x, y) _FMon_VN_ANGULAR_RATE_hytech((x), (y))
#define FMon_REAR_SUSPENSION_hytech(x, y) _FMon_REAR_SUSPENSION_hytech((x), (y))
#define FMon_SAB_THERMISTORS_1_hytech(x, y) _FMon_SAB_THERMISTORS_1_hytech((x), (y))
#define FMon_SAB_THERMISTORS_2_hytech(x, y) _FMon_SAB_THERMISTORS_2_hytech((x), (y))
#define FMon_VN_ECEF_POS_XY_hytech(x, y) _FMon_VN_ECEF_POS_XY_hytech((x), (y))
#define FMon_TCU_STATUS_hytech(x, y) _FMon_TCU_STATUS_hytech((x), (y))
#define FMon_VN_ECEF_POS_Z_MSG_hytech(x, y) _FMon_VN_ECEF_POS_Z_MSG_hytech((x), (y))
#define FMon_VN_GNSS_COMP_SIG_HEALTH_hytech(x, y) _FMon_VN_GNSS_COMP_SIG_HEALTH_hytech((x), (y))
#define FMon_DASHBOARD_MCU_STATE_hytech(x, y) _FMon_DASHBOARD_MCU_STATE_hytech((x), (y))
#define FMon_DASHBOARD_STATE_hytech(x, y) _FMon_DASHBOARD_STATE_hytech((x), (y))
#define FMon_FRONT_SUSPENSION_hytech(x, y) _FMon_FRONT_SUSPENSION_hytech((x), (y))
#define FMon_DRIVEBRAIN_TORQUE_LIM_INPUT_hytech(x, y) _FMon_DRIVEBRAIN_TORQUE_LIM_INPUT_hytech((x), (y))
#define FMon_DRIVEBRAIN_SPEED_SET_INPUT_hytech(x, y) _FMon_DRIVEBRAIN_SPEED_SET_INPUT_hytech((x), (y))
#define FMon_DRIVEBRAIN_DESIRED_TORQUE_INPUT_hytech(x, y) _FMon_DRIVEBRAIN_DESIRED_TORQUE_INPUT_hytech((x), (y))
#define FMon_FRONT_THERMISTORS_hytech(x, y) _FMon_FRONT_THERMISTORS_hytech((x), (y))
#define FMon_EM_MEASUREMENT_hytech(x, y) _FMon_EM_MEASUREMENT_hytech((x), (y))
#define FMon_MCU_ERROR_STATES_hytech(x, y) _FMon_MCU_ERROR_STATES_hytech((x), (y))
#define FMon_INV4_CONTROL_INPUT_hytech(x, y) _FMon_INV4_CONTROL_INPUT_hytech((x), (y))
#define FMon_INV1_CONTROL_PARAMETER_hytech(x, y) _FMon_INV1_CONTROL_PARAMETER_hytech((x), (y))
#define FMon_INV2_CONTROL_PARAMETER_hytech(x, y) _FMon_INV2_CONTROL_PARAMETER_hytech((x), (y))
#define FMon_INV3_CONTROL_PARAMETER_hytech(x, y) _FMon_INV3_CONTROL_PARAMETER_hytech((x), (y))
#define FMon_INV4_CONTROL_PARAMETER_hytech(x, y) _FMon_INV4_CONTROL_PARAMETER_hytech((x), (y))
#define FMon_ENERGY_METER_MEAS_hytech(x, y) _FMon_ENERGY_METER_MEAS_hytech((x), (y))
#define FMon_DRIVETRAIN_COMMAND_hytech(x, y) _FMon_DRIVETRAIN_COMMAND_hytech((x), (y))
#define FMon_INV1_OVERLOAD_hytech(x, y) _FMon_INV1_OVERLOAD_hytech((x), (y))
#define FMon_INV2_OVERLOAD_hytech(x, y) _FMon_INV2_OVERLOAD_hytech((x), (y))
#define FMon_INV3_OVERLOAD_hytech(x, y) _FMon_INV3_OVERLOAD_hytech((x), (y))
#define FMon_INV4_OVERLOAD_hytech(x, y) _FMon_INV4_OVERLOAD_hytech((x), (y))
#define FMon_DRIVETRAIN_RPMS_TELEM_hytech(x, y) _FMon_DRIVETRAIN_RPMS_TELEM_hytech((x), (y))
#define FMon_DRIVETRAIN_ERR_STATUS_TELEM_hytech(x, y) _FMon_DRIVETRAIN_ERR_STATUS_TELEM_hytech((x), (y))
#define FMon_DRIVETRAIN_STATUS_TELEM_hytech(x, y) _FMon_DRIVETRAIN_STATUS_TELEM_hytech((x), (y))
#define FMon_DRIVETRAIN_TORQUE_TELEM_hytech(x, y) _FMon_DRIVETRAIN_TORQUE_TELEM_hytech((x), (y))
#define FMon_DRIVETRAIN_FILTER_OUT_TORQUE_TEL_hytech(x, y) _FMon_DRIVETRAIN_FILTER_OUT_TORQUE_TEL_hytech((x), (y))
#define FMon_CAR_STATES_hytech(x, y) _FMon_CAR_STATES_hytech((x), (y))
#define FMon_DRIVEBRAIN_STATE_DATA_hytech(x, y) _FMon_DRIVEBRAIN_STATE_DATA_hytech((x), (y))
#define FMon_DASH_INPUT_hytech(x, y) _FMon_DASH_INPUT_hytech((x), (y))
#define FMon_AERO_PRESSURE_SENSOR_22_hytech(x, y) _FMon_AERO_PRESSURE_SENSOR_22_hytech((x), (y))
#define FMon_AERO_PRESSURE_SENSOR_32_hytech(x, y) _FMon_AERO_PRESSURE_SENSOR_32_hytech((x), (y))
#define FMon_AERO_PRESSURE_SENSOR_42_hytech(x, y) _FMon_AERO_PRESSURE_SENSOR_42_hytech((x), (y))
#define FMon_AERO_PRESSURE_SENSOR_11_hytech(x, y) _FMon_AERO_PRESSURE_SENSOR_11_hytech((x), (y))
#define FMon_AERO_PRESSURE_SENSOR_12_hytech(x, y) _FMon_AERO_PRESSURE_SENSOR_12_hytech((x), (y))
#define FMon_EM_STATUS_hytech(x, y) _FMon_EM_STATUS_hytech((x), (y))
#define FMon_ACU_SHUNT_MEASUREMENTS_hytech(x, y) _FMon_ACU_SHUNT_MEASUREMENTS_hytech((x), (y))
#define FMon_ENERGY_METER_STATUS_hytech(x, y) _FMon_ENERGY_METER_STATUS_hytech((x), (y))
#define FMon_STATE_OF_CHARGE_hytech(x, y) _FMon_STATE_OF_CHARGE_hytech((x), (y))
#define FMon_STEERING_DATA_hytech(x, y) _FMon_STEERING_DATA_hytech((x), (y))
#define FMon_LF_TTPMS_1_hytech(x, y) _FMon_LF_TTPMS_1_hytech((x), (y))
#define FMon_LF_TTPMS_2_hytech(x, y) _FMon_LF_TTPMS_2_hytech((x), (y))
#define FMon_LF_TTPMS_3_hytech(x, y) _FMon_LF_TTPMS_3_hytech((x), (y))
#define FMon_LF_TTPMS_4_hytech(x, y) _FMon_LF_TTPMS_4_hytech((x), (y))
#define FMon_LF_TTPMS_5_hytech(x, y) _FMon_LF_TTPMS_5_hytech((x), (y))
#define FMon_LF_TTPMS_6_hytech(x, y) _FMon_LF_TTPMS_6_hytech((x), (y))
#define FMon_LR_TTPMS_1_hytech(x, y) _FMon_LR_TTPMS_1_hytech((x), (y))
#define FMon_LR_TTPMS_2_hytech(x, y) _FMon_LR_TTPMS_2_hytech((x), (y))
#define FMon_LR_TTPMS_3_hytech(x, y) _FMon_LR_TTPMS_3_hytech((x), (y))
#define FMon_LR_TTPMS_4_hytech(x, y) _FMon_LR_TTPMS_4_hytech((x), (y))
#define FMon_LR_TTPMS_5_hytech(x, y) _FMon_LR_TTPMS_5_hytech((x), (y))
#define FMon_LR_TTPMS_6_hytech(x, y) _FMon_LR_TTPMS_6_hytech((x), (y))
#define FMon_RF_TTPMS_1_hytech(x, y) _FMon_RF_TTPMS_1_hytech((x), (y))
#define FMon_RF_TTPMS_2_hytech(x, y) _FMon_RF_TTPMS_2_hytech((x), (y))
#define FMon_RF_TTPMS_3_hytech(x, y) _FMon_RF_TTPMS_3_hytech((x), (y))
#define FMon_RF_TTPMS_4_hytech(x, y) _FMon_RF_TTPMS_4_hytech((x), (y))
#define FMon_RF_TTPMS_5_hytech(x, y) _FMon_RF_TTPMS_5_hytech((x), (y))
#define FMon_RF_TTPMS_6_hytech(x, y) _FMon_RF_TTPMS_6_hytech((x), (y))
#define FMon_RR_TTPMS_1_hytech(x, y) _FMon_RR_TTPMS_1_hytech((x), (y))
#define FMon_RR_TTPMS_2_hytech(x, y) _FMon_RR_TTPMS_2_hytech((x), (y))
#define FMon_RR_TTPMS_3_hytech(x, y) _FMon_RR_TTPMS_3_hytech((x), (y))
#define FMon_RR_TTPMS_4_hytech(x, y) _FMon_RR_TTPMS_4_hytech((x), (y))
#define FMon_RR_TTPMS_5_hytech(x, y) _FMon_RR_TTPMS_5_hytech((x), (y))
#define FMon_RR_TTPMS_6_hytech(x, y) _FMon_RR_TTPMS_6_hytech((x), (y))
#define FMon_BRAKE_ROTOR_SENSOR_COMMAND_hytech(x, y) _FMon_BRAKE_ROTOR_SENSOR_COMMAND_hytech((x), (y))
#define FMon_FL_BRAKE_ROTOR_TEMP_CH1_CH4_hytech(x, y) _FMon_FL_BRAKE_ROTOR_TEMP_CH1_CH4_hytech((x), (y))
#define FMon_FL_BRAKE_ROTOR_TEMP_CH5_CH8_hytech(x, y) _FMon_FL_BRAKE_ROTOR_TEMP_CH5_CH8_hytech((x), (y))
#define FMon_FL_BRAKE_ROTOR_TEMP_CH9_CH12_hytech(x, y) _FMon_FL_BRAKE_ROTOR_TEMP_CH9_CH12_hytech((x), (y))
#define FMon_FL_BRAKE_ROTOR_TEMP_CH13_CH16_hytech(x, y) _FMon_FL_BRAKE_ROTOR_TEMP_CH13_CH16_hytech((x), (y))
#define FMon_FL_BRAKE_ROTOR_SENSOR_TEMP_hytech(x, y) _FMon_FL_BRAKE_ROTOR_SENSOR_TEMP_hytech((x), (y))
#define FMon_FR_BRAKE_ROTOR_TEMP_CH1_CH4_hytech(x, y) _FMon_FR_BRAKE_ROTOR_TEMP_CH1_CH4_hytech((x), (y))
#define FMon_FR_BRAKE_ROTOR_TEMP_CH5_CH8_hytech(x, y) _FMon_FR_BRAKE_ROTOR_TEMP_CH5_CH8_hytech((x), (y))
#define FMon_FR_BRAKE_ROTOR_TEMP_CH9_CH12_hytech(x, y) _FMon_FR_BRAKE_ROTOR_TEMP_CH9_CH12_hytech((x), (y))
#define FMon_FR_BRAKE_ROTOR_TEMP_CH13_CH16_hytech(x, y) _FMon_FR_BRAKE_ROTOR_TEMP_CH13_CH16_hytech((x), (y))
#define FMon_FR_BRAKE_ROTOR_SENSOR_TEMP_hytech(x, y) _FMon_FR_BRAKE_ROTOR_SENSOR_TEMP_hytech((x), (y))
#define FMon_CONTROLLER_PID_TV_DATA_hytech(x, y) _FMon_CONTROLLER_PID_TV_DATA_hytech((x), (y))
#define FMon_CONTROLLER_PID_TV_DELTA_DATA_hytech(x, y) _FMon_CONTROLLER_PID_TV_DELTA_DATA_hytech((x), (y))
#define FMon_TCMUX_STATUS_REPORT_hytech(x, y) _FMon_TCMUX_STATUS_REPORT_hytech((x), (y))
#define FMon_ACU_OK_hytech(x, y) _FMon_ACU_OK_hytech((x), (y))
#define FMon_ENERGY_METER_TEMP_hytech(x, y) _FMon_ENERGY_METER_TEMP_hytech((x), (y))
#define FMon_AERO_PRESSURE_SENSOR_21_hytech(x, y) _FMon_AERO_PRESSURE_SENSOR_21_hytech((x), (y))
#define FMon_AERO_PRESSURE_SENSOR_31_hytech(x, y) _FMon_AERO_PRESSURE_SENSOR_31_hytech((x), (y))
#define FMon_AERO_PRESSURE_SENSOR_41_hytech(x, y) _FMon_AERO_PRESSURE_SENSOR_41_hytech((x), (y))
#define FMon_CONTROLLER_TCS_PID_OUTPUT_hytech(x, y) _FMon_CONTROLLER_TCS_PID_OUTPUT_hytech((x), (y))
#define FMon_VEHM_WHEEL_LIN_VEL_hytech(x, y) _FMon_VEHM_WHEEL_LIN_VEL_hytech((x), (y))
#define FMon_CONTROLLER_TORQUE_BIAS_hytech(x, y) _FMon_CONTROLLER_TORQUE_BIAS_hytech((x), (y))
#define FMon_CONTROLLER_REGEN_5KPH_TORQUE_hytech(x, y) _FMon_CONTROLLER_REGEN_5KPH_TORQUE_hytech((x), (y))
#define FMon_CONTROLLER_REGEN_5KPH_STATUS_hytech(x, y) _FMon_CONTROLLER_REGEN_5KPH_STATUS_hytech((x), (y))
#define FMon_CONTROLLER_TCS_PID_CONFIG_hytech(x, y) _FMon_CONTROLLER_TCS_PID_CONFIG_hytech((x), (y))
#define FMon_CONTROLLER_YAW_PID_CONFIG_hytech(x, y) _FMon_CONTROLLER_YAW_PID_CONFIG_hytech((x), (y))
#define FMon_CONTROLLER_TCS_SATURATION_CONFIG_hytech(x, y) _FMon_CONTROLLER_TCS_SATURATION_CONFIG_hytech((x), (y))
#define FMon_CONTROLLER_TCS_CONFIG_CONT_hytech(x, y) _FMon_CONTROLLER_TCS_CONFIG_CONT_hytech((x), (y))
#define FMon_CONTROLLER_TCS_DIFF_CONFIG_hytech(x, y) _FMon_CONTROLLER_TCS_DIFF_CONFIG_hytech((x), (y))
#define FMon_CONTROLLER_TCS_RPM_SCHE_CONFIG_hytech(x, y) _FMon_CONTROLLER_TCS_RPM_SCHE_CONFIG_hytech((x), (y))
#define FMon_CONTROLLER_TCS_SLIP_TARGETS_hytech(x, y) _FMon_CONTROLLER_TCS_SLIP_TARGETS_hytech((x), (y))
#define FMon_VEHM_WHEEL_STEER_AVG_DEG_MSG_hytech(x, y) _FMon_VEHM_WHEEL_STEER_AVG_DEG_MSG_hytech((x), (y))
#define FMon_VEHM_KIN_DES_YAW_RATE_RAD_S_MSG_hytech(x, y) _FMon_VEHM_KIN_DES_YAW_RATE_RAD_S_MSG_hytech((x), (y))
#define FMon_CONTROLLER_TCS_NL_SCHE_CONFIG_hytech(x, y) _FMon_CONTROLLER_TCS_NL_SCHE_CONFIG_hytech((x), (y))
#define FMon_CONTROLLER_PID_YAW_hytech(x, y) _FMon_CONTROLLER_PID_YAW_hytech((x), (y))
#define FMon_VEHM_LONG_CORNER_VEL_hytech(x, y) _FMon_VEHM_LONG_CORNER_VEL_hytech((x), (y))
#define FMon_VEHM_SL_hytech(x, y) _FMon_VEHM_SL_hytech((x), (y))
#define FMon_CONTROLLER_PID_YAW_TORQUE_hytech(x, y) _FMon_CONTROLLER_PID_YAW_TORQUE_hytech((x), (y))
#define FMon_CONTROLLER_NORMAL_DIST_hytech(x, y) _FMon_CONTROLLER_NORMAL_DIST_hytech((x), (y))
#define FMon_CONTROLLER_NORMAL_TORQUE_hytech(x, y) _FMon_CONTROLLER_NORMAL_TORQUE_hytech((x), (y))
#define FMon_CONTROLLER_POWER_LIM_hytech(x, y) _FMon_CONTROLLER_POWER_LIM_hytech((x), (y))
#define FMon_CONTROLLER_POWER_LIM_CORNER_POW_hytech(x, y) _FMon_CONTROLLER_POWER_LIM_CORNER_POW_hytech((x), (y))
#define FMon_CONTROLLER_POWER_LIM_TORQUE_hytech(x, y) _FMon_CONTROLLER_POWER_LIM_TORQUE_hytech((x), (y))
#define FMon_CONTROLLER_BOOLEAN_hytech(x, y) _FMon_CONTROLLER_BOOLEAN_hytech((x), (y))
#define FMon_VEHM_BETA_hytech(x, y) _FMon_VEHM_BETA_hytech((x), (y))
#define FMon_DASHBOARD_BUZZER_CONTROL_hytech(x, y) _FMon_DASHBOARD_BUZZER_CONTROL_hytech((x), (y))
#define FMon_CONTROLLER_TORQUE_SETUP_hytech(x, y) _FMon_CONTROLLER_TORQUE_SETUP_hytech((x), (y))
#define FMon_CONTROLLER_TCS_CONFIG_hytech(x, y) _FMon_CONTROLLER_TCS_CONFIG_hytech((x), (y))
#define FMon_CONTROLLER_TCS_TORQUE_hytech(x, y) _FMon_CONTROLLER_TCS_TORQUE_hytech((x), (y))
#define FMon_CONTROLLER_TCS_STATUS_hytech(x, y) _FMon_CONTROLLER_TCS_STATUS_hytech((x), (y))
#define FMon_CONTROLLER_TCS_PID_INPUT_hytech(x, y) _FMon_CONTROLLER_TCS_PID_INPUT_hytech((x), (y))
#define FMon_VEHM_ALPHA_hytech(x, y) _FMon_VEHM_ALPHA_hytech((x), (y))
#define FMon_CHARGER_CONTROL_hytech(x, y) _FMon_CHARGER_CONTROL_hytech((x), (y))
#define FMon_CHARGER_DATA_hytech(x, y) _FMon_CHARGER_DATA_hytech((x), (y))

#endif

#endif // HYTECH_USE_DIAG_MONITORS

#ifdef __cplusplus
}
#endif
